d3_tree_diagram:
  jshead: [js/jquery-1.8.2.min.js, js/d3.v3.min.js, js/treediagram.js]
  css: [css/style.css]
  cdn:
    jshead: 
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_tree_diagram/js/jquery-1.8.2.min.js"
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_tree_diagram/js/d3.v3.min.js"
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_tree_diagram/js/treediagram.js"
    css: 
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_tree_diagram/css/style.css"