d3_tree_diagram:
  jshead: [js/jquery-1.8.2.min.js, js/d3.v3.min.js, js/treediagram.js]
  css: [css/style.css]
  cdn:
    jshead:
      - "/pi/static/custom/jquery-1.8.2.min.js"
      - "/pi/static/custom/d3.v3.min-new.js"
    css:
      - "/pi/static/custom/treediagram.css"
