d3_horizon:
  jshead: [js/d3.v3.js,js/horizon.js]
  cdn:
    css:
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_horizon/css/base.css"
    jshead: 
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_horizon/js/d3.v3.js"
      - "https://s3.amazonaws.com/ada-pI/static/rCharts/libs/d3_horizon/js/horizon.js"
